# Generated by Django 3.2.6 on 2022-03-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddonare',
            name='contact_number',
            field=models.IntegerField(),
        ),
    ]
