# Generated by Django 3.2.6 on 2022-03-27 08:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_fooddonare_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddonare',
            name='donate_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
