# Generated by Django 4.0.3 on 2022-04-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodacceptor',
            name='contact_number',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='fooddonare',
            name='contact_number',
            field=models.CharField(max_length=12),
        ),
    ]
